I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 177, in script
    $ frienship_points += 1
  File "game/script.rpy", line 177, in <module>
    $ frienship_points += 1
NameError: name 'frienship_points' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 177, in script
    $ frienship_points += 1
  File "C:\Users\Esana\Documents\Others\elixir\renpy-6.99.12-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Esana\Documents\Others\elixir\renpy-6.99.12-sdk\renpy\python.py", line 1695, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 177, in <module>
    $ frienship_points += 1
NameError: name 'frienship_points' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.2003
Summer Break 0.0
